---

- name: check whether zsh exists or not
  stat: path=/home/vagrant/.oh-my-zsh
  register: zsh_installed

- name: zsh install
  apt: pkg=zsh state=present
  when: not zsh_installed.stat.exists

- name: Clone oh-my-zsh repo
  command: git clone git://github.com/robbyrussell/oh-my-zsh.git /home/vagrant/.oh-my-zsh
  when: not zsh_installed.stat.exists

- name: deploy .zshrc
  template: src=zshrc.cfg dest=/home/vagrant/.zshrc owner=vagrant

- name: change default shell
  user: name=vagrant shell=/usr/bin/zsh
  when: not zsh_installed.stat.exists