---

- name: check whether php5 exists or not
  stat: path=/etc/php5
  register: php5_installed

- name: php install
  apt: pkg={{item}} state=installed
  with_items:
  - php5
  - php5-cgi
  - php5-cli
  - libapache2-mod-php5
  - php5-common
  - php-pear
  - php5-mysql
  - php5-curl
  - php5-gd
  - imagemagick
  - php5-imagick
  - php5-mcrypt
  when: not apache2_installed.stat.exists

- template: src=php.ini dest=/etc/php5/apache2/php.ini owner=vagrant mode=0600
  when: not php5_installed.stat.exists

- command: sudo /etc/init.d/apache2 restart
  when: not php5_installed.stat.exists

# - name: apache service restart
#   service: name=apache2 state=restarted