---

- name: check whether mysql exists or not
  stat: path=/etc/mysql
  register: mysql_installed

- name: mysql install
  apt: pkg={{item}} state=installed
  with_items:
  - mysql-server
  when: not mysql_installed.stat.exists

- name: mysql root password setting
  mysql_user: name=root host={{item}} password={{root_db_password}}
  with_items:
    - 127.0.0.1
    - localhost
  when: not mysql_installed.stat.exists

- template: src=.my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600
  when: not mysql_installed.stat.exists

# - name: apache service restart
#   service: name=apache2 state=restarted